(define (phi x2)
  (<change>
    (not x2)
    x2))
(define (try f)
  (or (f #t)))
(define (sat-solve-4 pred)
  (try (lambda (n1)
         (try (lambda (n2)
                (pred n2))))))
(sat-solve-4 phi)