(letrec ((__toplevel_cons cons)
          (_0 (letrec ((init (lambda (ipats)
                               (let ()
                                 (letrec ((__do_loop (lambda (p)
                                                       (<change>
                                                         (if (null? ())
                                                           (set-cdr! p #f)
                                                           (() (() ())))
                                                         (set-cdr! p ())))))
                                   (__do_loop ipats))
                                 generate-symbol)))
                        (database (init
                                    (__toplevel_cons 'a ()))))
                ())))
  ())
