name: Daily Incremental MAF tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '00 22 * * 1,2,3,4' # Executes every night Mon-Thu at 23:00 CET or 00:00 CEST (schedule expressed in UTC).

jobs:
  # Checks whether the repository was updated within the last 25 hours (provide some overlap) and sets an environment flag.
  # Inspired by: * https://github.community/t/trigger-workflow-if-there-is-commit-in-last-24-hours/17074
  #              * https://github.com/rotators/Fo1in2/blob/33b3f45a9fd69757c8e8a5e698197cccadf8a1ae/.github/workflows/schedule.yml#L22-L65
  #activity-check:
  #  name: Activity check
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Activity check
  #      run: |
  #        curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits | jq -r '[.[]][0]' > $HOME/latest-commit.json
  #        date="$(jq -r '.commit.author.date' $HOME/latest-commit.json)"
  #        timestamp=$(date --utc -d "$date" +%s)
  #        hours=$(( ( $(date --utc +%s) - $timestamp ) / 3600 ))
  #        rm -f $HOME/latest-commit.json
  #        if [$hours -le 25]; then
  #          echo ::set-env name=MAF_REPO_ACTIVE::true
  #        fi
  #      shell: bash


  # The compile job fetches the code and attempts to compile it.
  compile:
    name: Compile MAF
    runs-on: ubuntu-latest
    #  needs: activity-check
    #  if: env.MAF_REPO_ACTIVE == 'true'
    steps:
      # Send a notification to Slack.
      - name: Notify push
        id: slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: maf-logs
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # Check out the GitHub repository.
      - name: Checkout the repository
        uses: actions/checkout@v2
      # Compile the code.
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Compile MAF
        run: sbt compile


  # These jobs execute the soundness tests for the incremental analyses.

  test-soundness:
    name: Execute incremental soundness tests (using ${{ matrix.test_class }})
    runs-on: ubuntu-latest
    needs: compile
    timeout-minutes: 360 # 6 hours
    strategy:
      fail-fast: false
      matrix:
        test_class: [
          # IncrementalModFType, # ci-di-wi already covered (part = fast tests)
          # IncrementalModFCP, # ci-di-wi already covered (now trait)
          # IncrementalSmallStepModConcType, # ci-di-wi already covered (part = fast tests)
          # IncrementalSmallStepModConcCP, # ci-di-wi already covered (now trait)

          IncrementalModFTypeSlowCI_1,
          IncrementalModFTypeSlowCI_2,
          IncrementalModFTypeSlowCI_3,
          IncrementalModFTypeSlowNoCIWI_1,
          IncrementalModFTypeSlowNoCIWI_2,
          IncrementalModFTypeSlowNoCIWI_3,
          IncrementalModFTypeSlowWI_1,
          IncrementalModFTypeSlowWI_2,
          IncrementalModFTypeSlowWI_3,
          IncrementalModFTypeSlowCIWI_1,
          IncrementalModFTypeSlowCIWI_2,
          IncrementalModFTypeSlowCIWI_3,

          IncrementalModFCPSlowCI_1,
          IncrementalModFCPSlowCI_2,
          IncrementalModFCPSlowCI_3,
          IncrementalModFCPSlowNoCIWI_1,
          IncrementalModFCPSlowNoCIWI_2,
          IncrementalModFCPSlowNoCIWI_3,
          IncrementalModFCPSlowWI_1,
          IncrementalModFCPSlowWI_2,
          IncrementalModFCPSlowWI_3,
          IncrementalModFCPSlowCIWI_1,
          IncrementalModFCPSlowCIWI_2,
          IncrementalModFCPSlowCIWI_3,

          IncrementalSmallStepModConcTypeSlowNoCIWI_1,
          IncrementalSmallStepModConcTypeSlowNoCIWI_2,
          IncrementalSmallStepModConcTypeSlowNoCIWI_3,
          IncrementalSmallStepModConcTypeSlowCI_1,
          IncrementalSmallStepModConcTypeSlowCI_2,
          IncrementalSmallStepModConcTypeSlowCI_3,
          IncrementalSmallStepModConcTypeSlowWI_1,
          IncrementalSmallStepModConcTypeSlowWI_2,
          IncrementalSmallStepModConcTypeSlowWI_3,
          IncrementalSmallStepModConcTypeSlowCIWI_1,
          IncrementalSmallStepModConcTypeSlowCIWI_2,
          IncrementalSmallStepModConcTypeSlowCIWI_3,

          IncrementalSmallStepModConcCPSlowNoCIWI_1,
          IncrementalSmallStepModConcCPSlowNoCIWI_2,
          IncrementalSmallStepModConcCPSlowNoCIWI_3,
          IncrementalSmallStepModConcCPSlowCI_1,
          IncrementalSmallStepModConcCPSlowCI_2,
          IncrementalSmallStepModConcCPSlowCI_3,
          IncrementalSmallStepModConcCPSlowWI_1,
          IncrementalSmallStepModConcCPSlowWI_2,
          IncrementalSmallStepModConcCPSlowWI_3,
          IncrementalSmallStepModConcCPSlowCIWI_1,
          IncrementalSmallStepModConcCPSlowCIWI_2,
          IncrementalSmallStepModConcCPSlowCIWI_3,
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      # Compile the code.
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Run incremental tests
        run: sbt "maf/testOnly maf.test.modular.scheme.incremental.${{ matrix.test_class }}"
        env:
          LOG_ENV: ci
          LOG_LOCATION: log-${{ github.sha }}
      - name: Upload soundness tests timing results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Soundness tests timing results
          path: out/*.csv
      # If failed, update the Slack notification.
      - name: Notify slack fail
        if: failure() || cancelled()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          LOG_ENV: ci
          LOG_LOCATION: log-${{ github.sha }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: FAILED
          color: danger


  # The test-incremental-properties job executes tests for the incremental analyses that are not the standard soundness tests.

  test-incremental-properties:
    name: Execute incremental tests (using ${{ matrix.test_class }})
    runs-on: ubuntu-latest
    needs: compile
    timeout-minutes: 480 # 8 hours
    strategy:
      fail-fast: false
      matrix:
        test_class: [
          IncrementalModXMachineryTests,
          IncrementalModularSchemeTypeLatticeTests,
          IncrementalModularSchemeCPLatticeTests,

          ModFComparisonTestsWI,
          ModFComparisonTestsCIWI,
          ModFComparisonTestsCI,
          ModFComparisonTestsNoCIWICY,
          ModFComparisonTestsWICY,
          ModFComparisonTestsCIWICY,

          ModConcComparisonTestsWI,
          ModConcComparisonTestsCIWI,
          ModConcComparisonTestsCI,
          ModConcComparisonTestsNoCIWI,

          IncrementalModFTypeRestartTests,
          IncrementalModFCPRestartTests,
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      # Compile the code.
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Run incremental tests
        run: sbt "maf/testOnly maf.test.modular.scheme.incremental.${{ matrix.test_class }}"
        env:
          LOG_ENV: ci
          LOG_LOCATION: log-${{ github.sha }}
      # If failed, update the Slack notification.
      - name: Notify slack fail
        if: failure() || cancelled()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: FAILED
          color: danger


  # These jobs test whether the analysis result is WL independent.

#  test-WL-independence:
#    name: Execute incremental tests (using ${{ matrix.test_class }})
#    runs-on: ubuntu-latest
#    needs: compile
#    timeout-minutes: 480 # 8 hours
#    strategy:
#      fail-fast: false
#      matrix:
#        test_class: [
#          IncrementalModFCPWLIndependenceTestsWithoutWI,
#          IncrementalModFCPWLIndependenceTestsWithWI
#        ]
#    steps:
#      - name: Checkout the repository
#        uses: actions/checkout@v2
#      # Compile the code.
#      - name: Setup Scala
#        uses: olafurpg/setup-scala@v10
#        with:
#          java-version: openjdk@1.15
#      - name: Run incremental tests
#        run: sbt "maf/testOnly maf.test.modular.scheme.incremental.${{ matrix.test_class }}"
#        env:
#          LOG_ENV: ci
#          LOG_LOCATION: log-${{ github.sha }}
#      # If failed, update the Slack notification.
#      - name: Notify slack fail
#        if: failure() || cancelled()
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#        uses: voxmedia/github-action-slack-notify-build@v1
#        with:
#          message_id: ${{ steps.slack.outputs.message_id }}
#          channel: maf-logs
#          status: FAILED
#          color: danger



  notify-success:
    name: Notify success
    runs-on: ubuntu-latest
    needs: [
      test-soundness,
      test-incremental-properties,
     # test-WL-independence,
    ]
    steps:
      # Send a notification to Slack.
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: SUCCESS
          color: good
